### ISSUE TITLE
Bug: Access Token causing 401 Unauthorized - ID Token works fine

### ISSUE THREAD

**Issue by Lokicoule** [Lokicoule/nestjs-cognito#1064]
**Describe the bug**
An issue occurs with the `nestjs-cognito` package when using the Access Token from AWS Cognito for authentication. The ID Token works perfectly, but when using the Access Token, a 401 Unauthorized error is encountered.

**To Reproduce**
1.  Set up Cognito User Pool with standard configurations.
2. Obtain both the ID Token and Access Token after successful user login.
3. Use the Access Token to authenticate a request to the NestJS API.
4. Observe the 401 Unauthorized error.
5. Try the same request with the ID Token, and it succeeds.

**Expected behavior**
The Access Token should authenticate users successfully, just like the ID Token.

**Current Behavior**
Using the Access Token results in a 401 Unauthorized error, while the ID Token works without any issues.

**Help wanted**
Due to time constraints, I'm unable to dig deeper into this issue right now. If any developers have experience with Cognito's Access Token handling, your help would be greatly appreciated. PRs and suggestions are welcome!

**Additional Request**
For those who have successfully used the Access Token with this package, could you please provide more information about your configuration of the Cognito User Pool? This could help in identifying potential discrepancies or setup differences.

**Comment by aam1r** [comment]
Hi @Lokicoule,

I had the same issue but I fixed it by changing the `tokenUse` parameter in the configuration from the default `id` to `access`. Did you try this? It seemed to fix the problem for me.

Also, I'm curious — why is `id` the default recommendation? From my understanding of JWT best practices, ID Tokens should remain private in the backend, while Access Tokens are more suitable for authenticating API requests. Wouldn't `access` be the better default?

If you have any documentation from AWS or other sources explaining why `id` is recommended, I'd love to see it.

Thanks!

**Comment by Lokicoule** [comment]
Hi @aam1r,

Sorry for my delayed response and thank you for taking the time to help!

You're absolutely right - a quick clarification on token usage:
- Originally, we had to used **ID tokens** for **RBAC** because **Access tokens** had limited customization.
- Since Dec 2023, AWS added [Access token customization](https://aws.amazon.com/fr/about-aws/whats-new/2023/12/amazon-cognito-user-pools-customize-access-tokens/) to Cognito. This changes everything.

Current best practice (2024+):
-  Use **Access tokens** only
-  Add your custom claims directly to **Access tokens**
-  Skip **ID tokens** for API auth (they expose unnecessary user data)

Thanks for raising this!
