### ISSUE TITLE
Great start!

### ISSUE THREAD

**Issue by railsjack** [Lokicoule/nestjs-cognito#138]
Upon googling "nestjs aws cognito", I found this repository.
It seems still new one that much things needs to be implemented yet, but it's a really good start.
And, its structure and architecture looks so professional.
I believe that this package can become a great one.
Expecting much more in future...

**Comment by Lokicoule** [comment]
Hello Railjack,
I'm sorry, I didn't see your comment until today.
Thank you very much for this feedback, it's always nice to see its work valued.

Any ideas for new features are welcome, so feel free to suggest them ;-)
