### ISSUE TITLE
Invalid Access Token (@nestjs-cognito/auth)

### ISSUE THREAD

**Issue by MaiKaY** [Lokicoule/nestjs-cognito#153]
Hi Loïk,
do you have an idea why I am getting the `Invalid Access Token` in [`auth/lib/cognito/cognito.service.ts:42:13`](https://github.com/Lokicoule/nestjs-cognito/blob/main/packages/auth/lib/cognito/cognito.service.ts#L57-L59)?

I am passing the JWT within `Authorization` header prefixed with `Bearer` to my backend system. On my frontend I am using Amplify-Auth and I am generating the token with:
```typescript
const session = await Auth.currentSession();
jwt = session.getIdToken().getJwtToken();
```

That never made any troubles before 🙈

**Comment by Lokicoule** [comment]
Hello Maik,
I guess it's because you send the id token instead of the access one.

```ts
session.getAccessToken().getJwtToken();
```
I'm waiting for your response before investigating further.
I hope now everything is working as expected.

**Comment by Lokicoule** [comment]
Hello Maik, I cannot reproduce this issue with a valid access token.
I'm closing this as stale. Please let me know if this is resolved on your end afterwards. 
Thank you!

**Comment by MaiKaY** [comment]
Hi Loïk,
sorry for the late response, I haven't had time the last couple of days. Thanks for the hint to use `getAccessToken()`, it seems to work but with the access token I am facing now another error `Request is undefined or null`. I am researching which library is causing this, I will let you know in case it's this library.

**Comment by MaiKaY** [comment]
I found the issue on my end 🙈
I used `AuthorizationGuard` from `@nestjs-cognito/auth` within my resolver but it needs to be the `AuthorizationGuard` from `@nestjs-cognito/graphql` 💡

**Comment by Lokicoule** [comment]
I'm glad everything is working as expected 😄 

I hesitated to name it with the `Gql` prefix, but I chose to keep the same naming convention.
Maybe I was wrong 😮
