### ISSUE TITLE
CognitoJwtPayload for Unauthenticated Route

### ISSUE THREAD

**Issue by iquirino** [Lokicoule/nestjs-cognito#322]
Hey guys,

I have a route that will show different things based on the authentication, let's say, remove some private information for unauthenticated users.

How can I use @CognitoUser without @Authentication/@Authorization?

Thank you! ;)

**Comment by Lokicoule** [comment]
Hello Igor, 

If you want to use the `@CognitoUser` decorator without the `@Authentication` and `@Authorization` decorators, you'll need to inject the Cognito JWT payload into the request object manually or via another middleware. Once the payload is available in the request object, you can use the `@CognitoUser` decorator to extract the user information and pass it to the controller or service method.

Hope that's helpful! Don't hesitate to let me know if you need more information or if you have any specific goals or requirements.

**Comment by Lokicoule** [comment]
I'm not sure if you were asking whether you need to decorate the controller or the resolver, but the answer is no. This is demonstrated in an example from the @nestjs-cognito/auth#[README](https://github.com/Lokicoule/nestjs-cognito/blob/main/packages/auth/README.md), which you can utilize as follows:
```ts
@Controller("dogs")
export class DogsController {
  @Get()
  @Authentication()
  findAll(@CognitoUser() CognitoJwtPayload): string {
    return "This action returns all my dogs";
  }
}```

**Comment by iquirino** [comment]
First of all: @Authentication works only for classes:
![image](https://user-images.githubusercontent.com/881117/226718650-2f2f2349-d610-430e-8409-2b9d8f17d316.png)
![image](https://user-images.githubusercontent.com/881117/226718890-9d59bfc1-ae6b-4cf2-8245-a80340e06483.png)

Second, my route need to not enforce any authentication, but, have a cognito user in case of a logged in user.
I want to show just public data for not logged in users, and show the entire data for logged users.

I managed this creating a different endpoint for public access, like:
/kind/123 (private data)
/kind/123/public (public data)

Can we have any kind of optional authentication? Or have @CognitoUser for methods not decorated with nestjs-cognito stuffs?

**Comment by iquirino** [comment]
Have you read my last question?
