### ISSUE TITLE
Expecting 'CognitoService' to provide some utility methods like register, login

### ISSUE THREAD

**Issue by mohammadraasel** [Lokicoule/nestjs-cognito#346]
Hey!
I was expecting `@nestjs-cognito/auth` would provide something like the following:
```javascript
import { CognitoService } from @nestjs-cognito/auth

const cognitoService = new CognitoService()
const newUser = await cognitoService.register({ username, email, password })
const tokenPayload = await cognitoService.login({ email, password })
```

I was trying to create a new cognito user from the nestjs server! so currently I did not find a way to do this using this `@nestjs-cognito/auth` library.

Thanks :)

**Comment by Lokicoule** [comment]
Hello Mohammad!

In fact, the @nestjs-cognito/auth package is designed to support authentication and authorization purposes only.
The best way to do that if you decide to use the @nestjs-cognito packages collection, is to import the `CognitoAuthModule` module from `@nestjs-cognito/core` for example like this:

```ts
@Module({
  imports: [
    CognitoAuthModule.registerAsync({
      imports: [ConfigModule],
      useFactory: async (configService: ConfigService) => ({
        region: configService.get('COGNITO_REGION'),
        credentials: {
          accessKeyId: configService.get('COGNITO_ACCESS_KEY_ID'),
          secretAccessKey: configService.get('COGNITO_SECRET_ACCESS_KEY'),
        },
      }),
      inject: [ConfigService],
    }),
  ],
})
export class CognitoProviderModule {}
``` 

Then, you can inject the cognito client and use the @aws-sdk/client-cognito-identity-provider API like this:
```ts
import {
  AdminAddUserToGroupCommandInput,
  AdminAddUserToGroupCommandOutput,
  CognitoIdentityProvider,
} from '@aws-sdk/client-cognito-identity-provider';
import { InjectCognitoIdentityProvider } from '@nestjs-cognito/core';
import { Injectable } from '@nestjs/common';

@Injectable()
export class CognitoService {
  constructor(
    @InjectCognitoIdentityProvider()
    private readonly cognitoClient: CognitoIdentityProvider,
  ) {}

  public addUserToGroup(
    groupName: string,
    username: string,
    userPoolId: string,
  ): Promise<AdminAddUserToGroupCommandOutput> {
    const params: AdminAddUserToGroupCommandInput = {
      GroupName: groupName,
      UserPoolId: userPoolId,
      Username: username,
    };

    return new Promise((resolve, reject) => {
      this.cognitoClient.adminAddUserToGroup(params, (error, data) => {
        if (error) {
          reject(error);
        } else {
          resolve(data);
        }
      });
    });
  }
}
```

This code example was for adding a user to a group, but it's the same way to achieve your goal for user creation.

According to the [aws doc](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cognito-identity-provider/classes/admincreateusercommand.html), you will also need to define the credentials :
```ts
credentials: {
      accessKeyId: configService.get('COGNITO_ACCESS_KEY_ID'),
      secretAccessKey: configService.get('COGNITO_SECRET_ACCESS_KEY'),
},
```

I hope this is helpful!

**Comment by Lokicoule** [comment]
You can look at users-application microservice in this repository to some guidance: [fdo-backend](https://github.com/Lokicoule/fdo-backend/tree/main/apps/users-application/src)

**Comment by iamandrewluca** [comment]
My solution was to simply use `@aws-amplify/auth` with their AWS Cognito Hosted UI

note: I'm using a client-side Vite application

Somewhere before you render your application

```ts
import { Auth } from '@aws-amplify/auth';

Auth.configure({
	region: 'eu-east-1',
	userPoolId: 'eu-east-1_XXXXXXXXX',
	userPoolWebClientId: '2s8lpk5a54ln...',
	oauth: {
		domain: 'your-cognito-domain.auth.eu-east-1.amazoncognito.com',
		scope: ['email', 'openid'],
		redirectSignIn: 'http://localhost:5173/',
		redirectSignOut: 'http://localhost:5173/',
		responseType: 'code',
	},
});
```

Somewhere else in the code

```ts
import { Auth } from '@aws-amplify/auth';

// ...
Auth.federatedSignIn() // Will redirect to Cognito Hosted UI
Auth.signOut() // logout

const userSession = await Auth.currentSession(); // get user session tokens
const token = userSession.idToken.jwtToken // use this as Authorization token
```

On the backend side, configure `@nestjs-cognito/auth` Cognito user pool and client id
Everything works.

You can read more about `@aws-amplify/auth` module here
https://docs.amplify.aws/lib/auth/social/q/platform/js/#setup-frontend
