### ISSUE TITLE
`jwksCache` option to avoid a time out error

### ISSUE THREAD

**Issue by ikeda1729** [Lokicoule/nestjs-cognito#515]
I encountered a cognito timeout error  describe in:
https://github.com/awslabs/aws-jwt-verify/issues/72#issuecomment-1139609992

To avoid this error, `jwksCache` option is necessary.
To fix this, the code in cognito.utils.js should be like this:
`    const { userPoolId, clientId, tokenUse = "id", additionalProperties, ...others } = cognitoModuleOptions.jwtVerifier;`

Should I make the PR for this?

**Comment by Lokicoule** [comment]
Hello @ikeda1729,

Thank you for bringing this issue to my attention and for offering to create a PRt. I appreciate your willingness to contribute to the project, please feel free to create a PR next time!

However, I have already made the necessary changes and published a new version (v1.1.0) of the `@nestjs-cognito/core` module. I hope this resolves the issue you were experiencing. (Don't forget to update `@nestjs-cognito/auth` to 1.0.5)

Thank you again Yusuke for your help in improving this project.

**Comment by ikeda1729** [comment]
Thank you for your reply, @Lokicoule.

Oh, you already fix this issue.
My version was `"@nestjs-cognito/auth": "^1.0.2",`.
I will update my project.

Thank you.
