### ISSUE TITLE
Support: Multiple Cognito User Pools

### ISSUE THREAD

**Issue by pivstone** [Lokicoule/nestjs-cognito#652]
Do you know how can I add multiple user pools? 

I assume this way will not working at all, right?
```ts
imports: [
    CognitoAuthModule.register({
      jwtVerifier: {
        userPoolId: "user_pool_2_id",
        clientId: "client_2_id",
        tokenUse: "id",
      },
    }),
   CognitoAuthModule.register({
      jwtVerifier: {
        userPoolId: "user_pool_id",
        clientId: "client_id",
        tokenUse: "id",
      },
    }),
  ],
```

**Comment by pscanlon1** [comment]
Did you find a solution to this? I have a use case where we have a user pool for external users, and I want to create another pool for server to server communication...

**Comment by mikhin** [comment]
@pivstone, @pscanlon1, hi! Can you please tell me how you solved this problem?

**Comment by pivstone** [comment]
Sorry, we don't have a solution for it base on this lib. Because we are using AppSync with cognito . So we just trust the request from AppSync and use their request context to get identity info.
FYI, aws AppSync will support private VPC.

**Comment by Lokicoule** [comment]
Hello,
@nestjs-cognito/auth package now supports multiple Cognito user pools in NestJS app with version [1.1.4](https://www.npmjs.com/package/@nestjs-cognito/auth/v/1.1.4).
