### ISSUE TITLE
Question: is there a way to load additional user information from database?

### ISSUE THREAD

**Issue by okonon** [Lokicoule/nestjs-cognito#771]
@Lokicoule thanks for such a cool library! Quick question for you: i am using access token that is sent from a mobile app to my api. I am assuming using access token is best practice. after this library validates access toke is there a way to "hook" into the process and look up user's aditional information in my own database using email from `@CognitoUser`?

thank you

**Comment by okonon** [comment]
aha have not even thought about that ! thank you very much !

**Comment by okonon** [comment]
@Lokicoule hi sorry to bother you again. I have pretty advanced use case so please bear with me as i try to explain.

 I am using `Casl` based `nestjs` [library](https://github.com/getjerry/nest-casl) to control user permissions and it expects "full" user object to be present in `request.user` property (i can control what that property name is).
So the problem is that above example that you suggested uses an interceptor to load "full" `domanUser` information from the database, however [interceptors are executed after guards](https://docs.nestjs.com/faq/request-lifecycle) therefore by the time `nestjs-casl` guard executes there is no "full" user object loaded to the request which results in 403 errors.

Do you have any other ideas how i can "hook" into your guard to run a DB query to get full user object ?

Again thank you so much for your help.

**Comment by okonon** [comment]
One idea that might work i refactor logic from `CurrentUser` Interceptor to a guard and place it after `AuthenticationGuard` and that should work. Any concerns with this approach ?

**Comment by Lokicoule** [comment]
It's a valid approach but did you try to use the user hook? 
```ts
....
import { COGNITO_USER_CONTEXT_PROPERTY } from "@nestjs-cognito/auth"; // export const COGNITO_USER_CONTEXT_PROPERTY = "cognito_user";

@Module({
  imports: [
    CaslModule.forRoot<Roles>({
      getUserFromRequest: (request) => request[COGNITO_USER_CONTEXT_PROPERTY],
      getUserHook: UserHook,
    }),
  ],
})
export class AppModule {}
```

```ts

import { Injectable } from '@nestjs/common';

import { UserBeforeFilterHook } from 'nest-casl';
import { UserService } from './user.service';
import { User } from './dtos/user.dto';

@Injectable()
export class UserHook implements UserBeforeFilterHook<User> {
  constructor(readonly userService: UserService) {}

  async run(user: User) {
    return {
      ...user,
      ...(await this.userService.findById(user.id)),
    };
  }
}
```

Source:
https://www.npmjs.com/package/nest-casl#advanced-usage

**Comment by okonon** [comment]
@Lokicoule yeah i tried using userHook and unfortunately it does not work because even if i use `getUserFromRequest: (request) => request[COGNITO_USER_CONTEXT_PROPERTY],` to set "current user" property so to speak Casl guard fails because user object does not have `roles` property with user roles (this is what i need to load from database). However `CurrentUserGuard` works:
```
import { CanActivate, ExecutionContext, Injectable } from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { AuthService } from '../../../private/auth/auth.service';
import { IS_PUBLIC_KEY } from '@nestjs-cognito/auth';
import { CURRENT_USER_CONTEXT_PROPERTY } from '../../constants';
import { LoggerService } from '@mycorp/nestjs-logger';

@Injectable()
export class CurrentUserGuard implements CanActivate {
  constructor(
    private reflector: Reflector,
    private readonly logger: LoggerService,
    private readonly authService: AuthService
  ) {
    this.logger.setContext(CurrentUserGuard.name);
  }

  async canActivate(context: ExecutionContext) {
    const request = context.switchToHttp().getRequest();
    try {
      // if route is public do not try to load user info
      const isPublic = this.reflector.getAllAndOverride<boolean>(IS_PUBLIC_KEY, [context.getHandler(), context.getClass()]);
      if (!isPublic) {
        let user = await this.authService.findDomainUser(request);
        if (!user) {
          // if user is not in our database then create user with information from cognito /userInfo endpoint
          user = await this.authService.createDomainUser(request);
        }
        // set current user request property to new or existing user
        request[CURRENT_USER_CONTEXT_PROPERTY] = user;
        if (request.method === 'POST' && request.body && !request.body.createdBy) {
          request.body.createdBy = user.id;
        }
        if (request.body && !request.body.updatedBy) {
          request.body.updatedBy = user.id;
        }
      }
    } catch (error) {
      this.logger.error(error);
    } finally {
      return true;
    }
  }
}
```
