### ISSUE TITLE
Multiple Cognito User Pools

### ISSUE THREAD

**Issue by mikhin** [Lokicoule/nestjs-cognito#790]
@Lokicoule, hi! Thanks for this effort on this lib—it is appreciated. 

Please tell me if there are some options to set up work with multiple user pools.

**Comment by Lokicoule** [comment]
Hey @mikhin, thank you for your support!

Unfortunately, it's not supported. I will do my best to add this feature at the beginning of 2024.

**Comment by Lokicoule** [comment]
Hey @mikhin,
Good news! @nestjs-cognito/auth package now supports multiple Cognito user pools in NestJS app with version [1.1.4](https://www.npmjs.com/package/@nestjs-cognito/auth/v/1.1.4).

**Comment by mikhin** [comment]
@Lokicoule, sounds great, thank you so much!

**Comment by Ev1ch** [comment]
Hello!

How to specify in `AuthenticationGuard` which user pool to use?
