### ISSUE TITLE
Randomly faced a 401 authentication failure upon starting the server

### ISSUE THREAD

**Issue by Willis0826** [Lokicoule/nestjs-cognito#796]
When I start the dev server locally, I notice that the first three or four requests to an API with `@UseGuards(AuthenticationGuard)` result in a 401 authentication failure.

However, after retrying the request a few times, it starts to work. I am unsure about the root cause of this flaky behavior. Here is how my API is set up.

`user.controller.ts`

```typescript
...
  @Get('')
  @UseGuards(AuthenticationGuard)
  @ApiBearerAuth()
  @ApiOkResponse({ type: UserEntity })
  @ApiOperation({ summary: 'Get the current user' })
  async getUserByAmplifyUserId(@CognitoUser() cognitoJwtPayload): Promise<User> {
    return await this.userService.user({ amplifyUserId: cognitoJwtPayload.sub })
  }
...
```

`app.module.ts`

```typescript
...
@Module({
  imports: [
    ConfigModule.forRoot(),
    CognitoAuthModule.registerAsync({
      imports: [ConfigModule],
      useFactory: async (configService: ConfigService) => ({
        jwtVerifier: {
          userPoolId: configService.get('COGNITO_USER_POOL_ID'),
          clientId: configService.get('COGNITO_CLIENT_ID'),
          tokenUse: 'id',
        },
      }),
      inject: [ConfigService]
    }),
    ...
})
export class AppModule { }
```

my package versions:
- @nestjs/common 10.2.10
- @nestjs/core 10.2.10
- @nestjs-cognito/auth 1.0.11
- @nestjs-cognito/core 1.1.7

**Comment by Willis0826** [comment]
To narrow down the possibilities, I can verify that the idToken I am using is valid with the following script.

```js
const jwt = require('jsonwebtoken');
const jwksClient = require('jwks-rsa');

const client = jwksClient({
  jwksUri: `https://cognito-idp.ap-northeast-1.amazonaws.com/{user pool id here}/.well-known/jwks.json`
});

function getKey(header, callback){
  client.getSigningKey(header.kid, function(err, key) {
    var signingKey = key.publicKey || key.rsaPublicKey;
    callback(null, signingKey);
  });
}

const idToken = 'my token here';
jwt.verify(idToken, getKey, {}, function(err, decoded) {
  if(err){
    console.log('Token is invalid:', err);
  } else {
    console.log('Token is valid:', decoded);
  }
});
```

**Comment by okonon** [comment]
@Willis0826 just an idea here. if you use `configService.getOrThrow` instead in your `useFactory` do you get any errors ? I am thinking if it is random maybe you have a race condition somewhere

**Comment by Lokicoule** [comment]
Hello @Willis0826,

Based on your provided code, I failed to reproduce it. Just like suggested @okonon it can be a configuration loading issue but it can also be a networking error or something like that.

Do you have more details and contexts to provide?

**Comment by Willis0826** [comment]
Sorry, I haven't had a chance to give it another look lately. I will try to find time to create a reproducible repository. Thanks
