### ISSUE TITLE
Nest can't resolve dependencies of the Service (ConfigService, ?). Please make sure that the argument COGNITO_IDENTITY_PROVIDER_INSTANCE_TOKEN at index [1] is available in the Module context.

### ISSUE THREAD

**Issue by mikhin** [Lokicoule/nestjs-cognito#808]
I have the following code:

```typescript
@Module({
  imports: [
    ConfigModule.forRoot({
      cache: true,
      isGlobal: true,
      load: [appConfig],
    }),
    CognitoModule.registerAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: async (configService: ConfigService<ApplicationConfig>) => {
        const cognitoClientID = configService.get('cognitoClientID');
        const cognitoMainRegion = configService.get('cognitoMainRegion');
        const cognitoUserPoolID = configService.get(
          'cognitoUserPoolID',
        ) as string;

        return {
          identityProvider: {
            region: cognitoMainRegion,
          },
          jwtVerifier: {
            clientId: cognitoClientID,
            tokenUse: 'id',
            userPoolId: cognitoUserPoolID,
          },
        };
      },
    }),
   Module,
  ],
})
export class AppModule {}
```

```typescript
import {
  CognitoIdentityProvider,
  ListUsersInGroupCommandOutput,
} from '@aws-sdk/client-cognito-identity-provider';
import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { InjectCognitoIdentityProvider } from '@nestjs-cognito/core';
import { ApplicationConfig } from '../app.config';

@Injectable()
export class Service {
  constructor(
    private configService: ConfigService<ApplicationConfig>,
    @InjectCognitoIdentityProvider()
    private readonly client: CognitoIdentityProvider,
  ) {}

  getList(): Promise<ListUsersInGroupCommandOutput> {
    const poolId = this.configService.get('cognitoUserPoolID');
    const GroupName = this.configService.get('cognitoGroupName');

    console.log(this.client);

    return this.client.listUsersInGroup({
      GroupName: GroupName,
      UserPoolId: poolId,
    });
  }
}
```

and I have the error: 

```
[Nest] 11596  - 01/08/2024, 4:16:31 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the Service (?, ConfigService). Please make sure that the argument COGNITO_IDENTITY_PROVIDER_INSTANCE_TOKEN at index [0] is available in the Module context.

Potential solutions:
- Is Module a valid NestJS module?
- If COGNITO_IDENTITY_PROVIDER_INSTANCE_TOKEN is a provider, is it part of the current Module?
- If COGNITO_IDENTITY_PROVIDER_INSTANCE_TOKEN is exported from a separate @Module, is that module imported within Module?
  @Module({
    imports: [ /* the Module containing COGNITO_IDENTITY_PROVIDER_INSTANCE_TOKEN */ ]
  })
```

How can i fix it?

**Comment by Lokicoule** [comment]
Hello @mikhin,

Can you please provide the module definition where you are injecting your `Service`?

**Comment by mikhin** [comment]
@Lokicoule , thanks for the fast response!

```typescript
import { Module } from '@nestjs/common';
import { AdminsController } from './admins.controller';
import { AdminsService } from './admins.service';

@Module({
  controllers: [AdminsController],
  providers: [AdminsService],
})
export class AdminsModule {}
```

**Comment by Lokicoule** [comment]
Thanks!

And where are you importing this `AdminsModule`?

**Comment by mikhin** [comment]
Sorry, for misspelling, it imported as `Module` in AppModule.

**Comment by Lokicoule** [comment]
I guess it's missing an import inside AdminsModule.

From my experience, it's better to have an atomic approach for managing module composition.

If you extract cognito registering logic to a new module let's call it `CognitoModule` and import this module inside your `AdminsModule` does it work?

For example only: (`@nestjs-cognito` version is outdated here so the DX is not the same)
https://github.com/Lokicoule/nestjs-graphql-boilerplate/blob/main/apps/users-application/src/cognito/cognito.provider.module.ts
https://github.com/Lokicoule/nestjs-graphql-boilerplate/blob/main/apps/users-application/src/users/presentation/users-presentation.module.ts

**Comment by mikhin** [comment]
Thank you!

I thought it was supposed to work globally if I import into an `AppModule`?

At least that's how it works with `CognitoAuthModule` - I do `registerAsync` in `AppModule` and then use `Authorization`, `CognitoUser` decorators in different modules, without additional imports within those modules.

**Comment by Lokicoule** [comment]
If you prefer to work with a global module you can decorate your new module `CognitoModule` with the `Global` decorator, it's up to you.

```ts
@Global()
@Module({
  imports: [
    CognitoAuthModule.registerAsync({
      imports: [ConfigModule],
      useFactory: async (configService: ConfigService) => ({
      ...
      }),
      inject: [ConfigService],
    }),
  ],
})
export class CognitoModule {}
```

**Comment by Lokicoule** [comment]
It's a very good point and I forgot about it, but it's as simple as that:
- `CognitoModule` from core package is not global
- `AuthCognitoModule` from auth package is global.

This design decision was made to simplify imports when using the auth package as the API entry point while enforcing specific importation requirements when using the core package.
In your initial code, instead of using `CognitoModule`, go for `AuthCognitoModule`. It essentially acts as a convenient adapter for `CognitoModule`, and it should work seamlessly.

**Comment by mikhin** [comment]
Thanks for clarifications and fast answers! Really appreciated!
