### ISSUE TITLE
Return `undefined` if used @CognitoUser without @Authentication or @Authorization

### ISSUE THREAD

**Issue by mikhin** [Lokicoule/nestjs-cognito#864]
Hi. Once again, I would like to thank you for your hard work, and I would want to ask a question.

Can we make changes so that the `@CognitoUser` decorator returns `undefined` or `null` in case the data is unavailable?

My case is a route that is accessible by two different authentication methods: Cognito JWT and another one.

```
@Post()
  async create(
    @CognitoUser('email') email?: string,
    @Headers(API_KEY_AUTH_HEADER) apiKey?: string,
  ): Promise {
```

Right now, I'm getting a 500 error and a `"message": "Cannot read properties of undefined (reading 'cognito:email'),` but I'd like the error not to be thrown, and I could process `undefined` or `null` as data from Cognito myself.

**Comment by Lokicoule** [comment]
Hello @mikhin,

Version `1.1.3` is now released! Feel free to create a PR next time!
I hope that meets your needs.

**Comment by mikhin** [comment]
@Lokicoule, wow! Thanks so much for the quick response and support. It is very much appreciated! <3
