### ISSUE TITLE
Feature Request: Support usage of JwtRsaVerifier supported by aws-jwt-verify

### ISSUE THREAD

**Issue by goistjt** [Lokicoule/nestjs-cognito#941]
**Is your feature request related to a problem? Please describe.**

I would like to use this library in a project using Localstack for development purposes, where the Cognito IDP is at an endpoint such as `https://cognito-idp.localhost.localstack.cloud/${userPoolId}`.

**Describe the solution you'd like**

Expand the `jwtVerifier` property when registering the `CognitoAuthModule` to accept input matching the shape outline in the `aws-jwt-verify` docs here https://github.com/awslabs/aws-jwt-verify?tab=readme-ov-file#using-the-generic-jwt-rsa-verifier-for-cognito-jwts in order to allow custom JWKS issuers.

**Describe alternatives you've considered**

I've attempted to set the `identityProvider.endpoint` property to the Localstack Cognito IDP, which allowed getting the JWKS correctly, but the default `CognitoJwtVerifier` that seems to be constructed through `CognitoAuthModule.registerAsync` is defaulting to use the `https://cognito-idp.<region>.amazonaws.com` domain for token issuer validation purposes, even though the localstack JWKS allows `http://localhost.localstack.cloud:4566/<userPoolId>` as an issuer.

**Additional context**

Registering the `CognitoAuthModule`:
```typescript
    CognitoAuthModule.registerAsync({
      imports: [forwardRef(() => ConfigModule)],
      useFactory: (configService: ConfigService) => {
        const clientId = configService.get<string>('COGNITO_CLIENT_ID');
        const userPoolId = configService.get<string>(
          'COGNITO_USER_POOL_ID'
        ) as string;
        return {
          jwtVerifier: {
            clientId,
            userPoolId,
            tokenUse: 'access',
            includeRawJwtInErrors: true,
          },
          identityProvider: {
            region: configService.get<string>('COGNITO_REGION');
            endpoint: `https://cognito-idp.localhost.localstack.cloud/${userPoolId}`,
          },
        };
      },
      inject: [ConfigService],
    })
 ```

**Comment by Lokicoule** [comment]
Hello @goistjt,

Please update to version [1.1.4] (https://www.npmjs.com/package/@nestjs-cognito/auth/v/1.1.4) and try again. More information is available at [@nestjs-core] (https://www.npmjs.com/package/@nestjs-cognito/core). Can you let me know if this release solves your need?

Thank you for your support.

**Comment by goistjt** [comment]
Hi @Lokicoule 

Thank you for the support, this worked perfectly for my use case! Feel free to close this issue 😄

**Comment by Lokicoule** [comment]
Thank you very much for your feedback!
